class ColumnName:
    """Constants for column names used in data processing and evaluation."""
    NO = "No"
    EXP_ID = "Exp ID"
    PROMPT = "Prompt"
    EXPECTED_SQL_QUERY = "Expected SQL Query"
    EXPECTED_QUERY_RESULT = "Expected Query Result"
    GENERATED_SQL_QUERY = "Generated SQL Query"
    GENERATED_QUERY_RESULT = "Generated Query Result"
    BASE_PROMPT = "Base Prompt"
    TIME_TAKEN = "Time Taken"
    FAILED_SQL_QUERY = "Failed SQL Query"
    ERROR = "Error"
    SQL_REASONING = "SQL Reasoning"
    REQUIRED_TABLES = "Required Tables"
    DATABASE_TYPE = "Database"

class ColumnMatrix:
    EXP_ID = "Exp ID"
    ACCURACY = "Accuracy"
    PRECISION = "Precision"
    RECALL = "Recall"
    F1_SCORE = "F1 Score"
    TIME_TAKEN = "Time Taken"
    AVG_ACCURACY = "Avg Accuracy"
    AVG_PRECISION = "Avg Precision"
    AVG_RECALL = "Avg Recall"
    AVG_F1_SCORE = "Avg F1 Score"
    GROUND_TRUTH_BUT_NOT_PREDICTED = "Ground Truth but not Predicted"
    PREDICTED_BUT_NOT_IN_GROUND_TRUTH = "Predicted but not in Ground Truth"